from datetime import datetime, timezone
from .extensions import db

def now():
    return datetime.now(timezone.utc)

class TimestampMixin:
    created_at = db.Column(db.DateTime(timezone=True), default=now, nullable=False)

class Company(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    real_budget_limit = db.Column(db.Numeric(12, 4), nullable=False)
    currency = db.Column(db.String(8), default="TWD", nullable=False)
    updated_at = db.Column(db.DateTime(timezone=True), default=now, onupdate=now, nullable=False)

class Department(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)
    description = db.Column(db.Text)
    active = db.Column(db.Boolean, default=True, nullable=False)

class Position(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    level = db.Column(db.Integer, nullable=False)
    description = db.Column(db.Text)

class ModelConfig(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    label = db.Column(db.String(120), nullable=False)
    provider_key = db.Column(db.String(40), nullable=False)
    model_name = db.Column(db.String(120), nullable=False)
    input_price_per_million = db.Column(db.Numeric(12, 4), default=0, nullable=False)
    output_price_per_million = db.Column(db.Numeric(12, 4), default=0, nullable=False)
    currency = db.Column(db.String(8), default="TWD", nullable=False)
    max_output_tokens = db.Column(db.Integer, default=1200, nullable=False)
    active = db.Column(db.Boolean, default=True, nullable=False)
    archived = db.Column(db.Boolean, default=False, nullable=False)

class Employee(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    slug = db.Column(db.String(120), unique=True, nullable=False)
    department_id = db.Column(db.Integer, db.ForeignKey("department.id"))
    position_id = db.Column(db.Integer, db.ForeignKey("position.id"), nullable=False)
    manager_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    role_description = db.Column(db.Text, nullable=False)
    system_instructions = db.Column(db.Text, nullable=False)
    current_model_config_id = db.Column(db.Integer, db.ForeignKey("model_config.id"))
    salary_credits_per_week = db.Column(db.Numeric(12, 2), default=0, nullable=False)
    active = db.Column(db.Boolean, default=True, nullable=False)
    employment_status = db.Column(db.String(20), default="ACTIVE", nullable=False)
    probation_target_assignments = db.Column(db.Integer)
    hiring_request_id = db.Column(db.Integer)
    updated_at = db.Column(db.DateTime(timezone=True), default=now, onupdate=now, nullable=False)
    department = db.relationship("Department")
    position = db.relationship("Position")
    manager = db.relationship("Employee", remote_side=[id])
    current_model = db.relationship("ModelConfig")

class EmployeeModelHistory(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    model_config_id = db.Column(db.Integer, db.ForeignKey("model_config.id"))
    reason = db.Column(db.Text)
    started_at = db.Column(db.DateTime(timezone=True), default=now, nullable=False)
    ended_at = db.Column(db.DateTime(timezone=True))
    model_config = db.relationship("ModelConfig")

class Project(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(160), nullable=False)
    objective = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(20), default="PLANNING", nullable=False)
    priority = db.Column(db.String(20), default="MEDIUM", nullable=False)
    environment = db.Column(db.String(20), default="LIVE", nullable=False)
    origin = db.Column(db.String(20), default="NEW", nullable=False)
    current_state_summary = db.Column(db.Text)
    known_constraints = db.Column(db.Text)
    next_milestone = db.Column(db.Text)
    owner_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    budget_credits = db.Column(db.Numeric(12, 2))
    real_budget_limit = db.Column(db.Numeric(12, 4))
    deadline = db.Column(db.DateTime(timezone=True))
    updated_at = db.Column(db.DateTime(timezone=True), default=now, onupdate=now, nullable=False)
    owner = db.relationship("Employee")

class Task(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"), nullable=False)
    operation_id = db.Column(db.Integer, db.ForeignKey("operation.id"))
    parent_task_id = db.Column(db.Integer, db.ForeignKey("task.id"))
    title = db.Column(db.String(180), nullable=False)
    objective = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(20), default="TODO", nullable=False)
    priority = db.Column(db.String(20), default="MEDIUM", nullable=False)
    created_by_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    assigned_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    reviewer_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    deadline = db.Column(db.DateTime(timezone=True))
    budget_credits = db.Column(db.Numeric(12, 2))
    required_output = db.Column(db.Text)
    acceptance_criteria = db.Column(db.Text)
    result_summary = db.Column(db.Text)
    updated_at = db.Column(db.DateTime(timezone=True), default=now, onupdate=now, nullable=False)
    completed_at = db.Column(db.DateTime(timezone=True))
    project = db.relationship("Project", backref="tasks")
    assigned_employee = db.relationship("Employee", foreign_keys=[assigned_employee_id])
    reviewer = db.relationship("Employee", foreign_keys=[reviewer_employee_id])

class Operation(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(180), nullable=False)
    objective = db.Column(db.Text, nullable=False)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    proposed_by_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    status = db.Column(db.String(30), default="PLANNED", nullable=False)
    plan_json = db.Column(db.JSON, nullable=False)
    approved_budget_twd = db.Column(db.Numeric(12, 4), nullable=False)
    actual_cost_twd = db.Column(db.Numeric(12, 6), default=0, nullable=False)
    founder_report_json = db.Column(db.JSON)
    memory_json = db.Column(db.JSON)
    waiting_reason = db.Column(db.Text)
    approved_at = db.Column(db.DateTime(timezone=True))
    ended_at = db.Column(db.DateTime(timezone=True))
    updated_at = db.Column(db.DateTime(timezone=True), default=now, onupdate=now, nullable=False)
    project = db.relationship("Project")
    proposed_by = db.relationship("Employee")
    tasks = db.relationship("Task", backref="operation", order_by="Task.id")

class OperationStep(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    operation_id = db.Column(db.Integer, db.ForeignKey("operation.id"), nullable=False)
    idempotency_key = db.Column(db.String(180), nullable=False)
    logical_key = db.Column(db.String(180))
    kind = db.Column(db.String(30), nullable=False)
    status = db.Column(db.String(20), default="CLAIMED", nullable=False)
    task_id = db.Column(db.Integer, db.ForeignKey("task.id"))
    agent_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"))
    result_json = db.Column(db.JSON)
    error_text = db.Column(db.Text)
    provider_started_at = db.Column(db.DateTime(timezone=True))
    finished_at = db.Column(db.DateTime(timezone=True))
    operation = db.relationship("Operation", backref="steps")
    task = db.relationship("Task")
    __table_args__ = (
        db.UniqueConstraint("operation_id", "idempotency_key"),
        db.UniqueConstraint("operation_id", "logical_key"),
    )

class WorkMessage(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    task_id = db.Column(db.Integer, db.ForeignKey("task.id"))
    sender_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    recipient_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    agent_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"))
    message_type = db.Column(db.String(20), nullable=False)
    content = db.Column(db.Text, nullable=False)

class AgentRun(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    task_id = db.Column(db.Integer, db.ForeignKey("task.id"))
    meeting_id = db.Column(db.Integer, db.ForeignKey("meeting.id"))
    operation_id = db.Column(db.Integer, db.ForeignKey("operation.id"))
    model_config_id = db.Column(db.Integer, db.ForeignKey("model_config.id"), nullable=False)
    purpose = db.Column(db.String(80), nullable=False)
    user_request = db.Column(db.Text, nullable=False)
    system_prompt_snapshot = db.Column(db.Text, nullable=False)
    context_snapshot = db.Column(db.Text, nullable=False)
    raw_output = db.Column(db.Text)
    parsed_output_json = db.Column(db.JSON)
    status = db.Column(db.String(20), default="CREATED", nullable=False)
    provider_request_id = db.Column(db.String(160))
    provider_response_id = db.Column(db.String(160))
    provider_stop_reason = db.Column(db.String(80))
    failure_reason = db.Column(db.String(80))
    context_composition_json = db.Column(db.JSON)
    response_schema_snapshot_json = db.Column(db.JSON)
    structured_validation_status = db.Column(db.String(30))
    structured_validation_warnings_json = db.Column(db.JSON)
    structured_validation_errors_json = db.Column(db.JSON)
    input_tokens = db.Column(db.Integer)
    output_tokens = db.Column(db.Integer)
    effective_max_output_tokens = db.Column(db.Integer)
    cache_creation_input_tokens = db.Column(db.Integer, default=0, nullable=False)
    cache_read_input_tokens = db.Column(db.Integer, default=0, nullable=False)
    real_cost = db.Column(db.Numeric(12, 6))
    currency = db.Column(db.String(8), default="TWD", nullable=False)
    provider_key_snapshot = db.Column(db.String(40), nullable=False)
    model_name_snapshot = db.Column(db.String(120), nullable=False)
    input_price_snapshot = db.Column(db.Numeric(12, 4), nullable=False)
    output_price_snapshot = db.Column(db.Numeric(12, 4), nullable=False)
    currency_snapshot = db.Column(db.String(8), nullable=False)
    error_text = db.Column(db.Text)
    resolution_status = db.Column(db.String(30))
    resolved_at = db.Column(db.DateTime(timezone=True))
    resolution_note = db.Column(db.Text)
    replacement_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"))
    started_at = db.Column(db.DateTime(timezone=True), default=now, nullable=False)
    finished_at = db.Column(db.DateTime(timezone=True))
    employee = db.relationship("Employee")
    model_config = db.relationship("ModelConfig")

class CostEvent(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey("company.id"), nullable=False)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    task_id = db.Column(db.Integer, db.ForeignKey("task.id"))
    agent_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"))
    operation_id = db.Column(db.Integer, db.ForeignKey("operation.id"))
    category = db.Column(db.String(30), nullable=False)
    description = db.Column(db.Text, nullable=False)
    internal_credits_delta = db.Column(db.Numeric(12, 2), default=0, nullable=False)
    real_cost_delta = db.Column(db.Numeric(12, 6), default=0, nullable=False)
    currency = db.Column(db.String(8), default="TWD", nullable=False)

class ContributionEvent(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    scope = db.Column(db.String(20), nullable=False)
    event_type = db.Column(db.String(40), nullable=False)
    value = db.Column(db.Numeric(12, 2), nullable=False)
    reason = db.Column(db.Text, nullable=False)
    related_task_id = db.Column(db.Integer, db.ForeignKey("task.id"))
    related_reference = db.Column(db.String(200))
    status = db.Column(db.String(20), default="PROVISIONAL", nullable=False)

class EmployeeLearningRecord(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    task_id = db.Column(db.Integer, db.ForeignKey("task.id"))
    title = db.Column(db.String(180), nullable=False)
    content = db.Column(db.Text, nullable=False)
    source_ref = db.Column(db.String(300))
    validated = db.Column(db.Boolean, default=False, nullable=False)

class TalentTemplate(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(160), nullable=False)
    role_title = db.Column(db.String(160), nullable=False)
    department_hint = db.Column(db.String(120))
    mission = db.Column(db.Text, nullable=False)
    responsibilities_json = db.Column(db.JSON, nullable=False)
    instructions = db.Column(db.Text, nullable=False)
    skills_json = db.Column(db.JSON, nullable=False)
    suggested_tools_json = db.Column(db.JSON, nullable=False)
    deliverables_json = db.Column(db.JSON, nullable=False)
    success_metrics_json = db.Column(db.JSON, nullable=False)
    source = db.Column(db.String(240), nullable=False)
    source_key = db.Column(db.String(300), unique=True, nullable=False)
    active_in_pool = db.Column(db.Boolean, default=True, nullable=False)
    suggested_model_class = db.Column(db.String(120))
    notes = db.Column(db.Text)

class HiringRequest(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    requested_by_type = db.Column(db.String(20), nullable=False)
    requester_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    operation_id = db.Column(db.Integer, db.ForeignKey("operation.id"))
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    talent_template_id = db.Column(db.Integer, db.ForeignKey("talent_template.id"))
    role_needed = db.Column(db.String(160), nullable=False)
    problem = db.Column(db.Text, nullable=False)
    why_now = db.Column(db.Text, nullable=False)
    responsibilities_json = db.Column(db.JSON, nullable=False)
    capabilities_json = db.Column(db.JSON, nullable=False)
    urgency = db.Column(db.String(20), nullable=False)
    use_frequency = db.Column(db.String(30), nullable=False)
    status = db.Column(db.String(30), default="REQUESTED", nullable=False)
    hr_assessment_json = db.Column(db.JSON)
    recommended_model_config_id = db.Column(db.Integer, db.ForeignKey("model_config.id"))
    assessment_budget_twd = db.Column(db.Numeric(12, 4))
    hr_agent_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"))
    target_department_id = db.Column(db.Integer, db.ForeignKey("department.id"))
    target_position = db.Column(db.String(160))
    manager_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    resource_envelope_json = db.Column(db.JSON)
    founder_decision = db.Column(db.String(20))
    founder_decision_note = db.Column(db.Text)
    founder_decided_at = db.Column(db.DateTime(timezone=True))
    created_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    updated_at = db.Column(db.DateTime(timezone=True), default=now, onupdate=now, nullable=False)
    requester = db.relationship("Employee", foreign_keys=[requester_employee_id])
    talent_template = db.relationship("TalentTemplate")
    recommended_model = db.relationship("ModelConfig")
    target_department = db.relationship("Department")
    approved_manager = db.relationship("Employee", foreign_keys=[manager_employee_id])
    created_employee = db.relationship("Employee", foreign_keys=[created_employee_id])

class KnowledgeItem(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    kind = db.Column(db.String(20), nullable=False)
    title = db.Column(db.String(180), nullable=False)
    content = db.Column(db.Text, nullable=False)
    rationale = db.Column(db.Text)
    source_ref = db.Column(db.String(300))
    origin_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    origin_agent_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"))
    founder_approved = db.Column(db.Boolean, default=False, nullable=False)
    target_knowledge_id = db.Column(db.Integer, db.ForeignKey("knowledge_item.id"))

class KnowledgeReference(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    from_knowledge_id = db.Column(db.Integer, db.ForeignKey("knowledge_item.id"), nullable=False)
    to_knowledge_id = db.Column(db.Integer, db.ForeignKey("knowledge_item.id"), nullable=False)
    relation_type = db.Column(db.String(30), nullable=False)

class Proposal(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    agent_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"), nullable=False)
    proposed_by_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    payload_json = db.Column(db.JSON, nullable=False)
    status = db.Column(db.String(20), default="PENDING", nullable=False)
    review_note = db.Column(db.Text)
    corrected_payload_json = db.Column(db.JSON)
    materialized_knowledge_id = db.Column(db.Integer, db.ForeignKey("knowledge_item.id"))
    reviewed_at = db.Column(db.DateTime(timezone=True))

class FounderInterview(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    started_at = db.Column(db.DateTime(timezone=True), default=now, nullable=False)
    ended_at = db.Column(db.DateTime(timezone=True))
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    employee = db.relationship("Employee")

class FounderInterviewMessage(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    interview_id = db.Column(db.Integer, db.ForeignKey("founder_interview.id"), nullable=False)
    speaker = db.Column(db.String(20), nullable=False)
    content = db.Column(db.Text, nullable=False)
    interview = db.relationship("FounderInterview", backref="messages")

class Meeting(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey("company.id"), nullable=False)
    project_id = db.Column(db.Integer, db.ForeignKey("project.id"))
    operation_id = db.Column(db.Integer, db.ForeignKey("operation.id"))
    title = db.Column(db.String(180), nullable=False)
    purpose = db.Column(db.Text, nullable=False)
    agenda = db.Column(db.Text, nullable=False)
    chair_employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    status = db.Column(db.String(30), default="PLANNED", nullable=False)
    current_round = db.Column(db.Integer, default=0, nullable=False)
    max_rounds = db.Column(db.Integer, default=3, nullable=False)
    token_limit = db.Column(db.Integer, default=12000, nullable=False)
    real_cost_limit_twd = db.Column(db.Numeric(12, 4), default=100, nullable=False)
    created_by = db.Column(db.String(20), default="FOUNDER", nullable=False)
    founder_joined_at = db.Column(db.DateTime(timezone=True))
    current_summary_json = db.Column(db.JSON)
    minutes_json = db.Column(db.JSON)
    started_at = db.Column(db.DateTime(timezone=True))
    ended_at = db.Column(db.DateTime(timezone=True))
    termination_reason = db.Column(db.Text)
    execution_profile = db.Column(db.String(20), default="STANDARD", nullable=False)
    max_speakers_per_round = db.Column(db.Integer, default=3, nullable=False)
    contribution_output_cap = db.Column(db.Integer, default=640, nullable=False)
    router_output_cap = db.Column(db.Integer, default=256, nullable=False)
    synthesis_output_cap = db.Column(db.Integer, default=768, nullable=False)
    routing_json = db.Column(db.JSON)
    last_blocked_json = db.Column(db.JSON)
    paid_failure_json = db.Column(db.JSON)
    project = db.relationship("Project")
    operation = db.relationship("Operation")
    chair = db.relationship("Employee")

class MeetingParticipant(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    meeting_id = db.Column(db.Integer, db.ForeignKey("meeting.id"), nullable=False)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    role = db.Column(db.String(80))
    joined_at = db.Column(db.DateTime(timezone=True), default=now, nullable=False)
    removed_at = db.Column(db.DateTime(timezone=True))
    employee = db.relationship("Employee")
    meeting = db.relationship("Meeting", backref="participants")
    __table_args__=(db.UniqueConstraint("meeting_id","employee_id"),)

class MeetingMessage(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    meeting_id = db.Column(db.Integer, db.ForeignKey("meeting.id"), nullable=False)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    speaker_type = db.Column(db.String(20), nullable=False)
    round_number = db.Column(db.Integer, default=0, nullable=False)
    message_type = db.Column(db.String(40), nullable=False)
    content = db.Column(db.Text, nullable=False)
    agent_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"))
    validation_status = db.Column(db.String(30))
    validation_warnings_json = db.Column(db.JSON)
    employee = db.relationship("Employee")
    meeting = db.relationship("Meeting", backref="messages")

class FounderFeedbackEvent(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    meeting_id = db.Column(db.Integer, db.ForeignKey("meeting.id"), nullable=False)
    message_id = db.Column(db.Integer, db.ForeignKey("meeting_message.id"), nullable=False)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"), nullable=False)
    signal = db.Column(db.String(30), nullable=False)
    note = db.Column(db.Text)

class MeetingStep(db.Model, TimestampMixin):
    id = db.Column(db.Integer, primary_key=True)
    meeting_id = db.Column(db.Integer, db.ForeignKey("meeting.id"), nullable=False)
    logical_key = db.Column(db.String(180), nullable=False)
    kind = db.Column(db.String(40), nullable=False)
    round_number = db.Column(db.Integer, default=0, nullable=False)
    employee_id = db.Column(db.Integer, db.ForeignKey("employee.id"))
    contribution_shape = db.Column(db.String(40))
    status = db.Column(db.String(20), default="PENDING", nullable=False)
    agent_run_id = db.Column(db.Integer, db.ForeignKey("agent_run.id"))
    result_json = db.Column(db.JSON)
    error_text = db.Column(db.Text)
    finished_at = db.Column(db.DateTime(timezone=True))
    meeting = db.relationship("Meeting", backref="steps")
    employee = db.relationship("Employee")
    __table_args__=(db.UniqueConstraint("meeting_id","logical_key"),)
